/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package magnetron_game_kotlin

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    val mag = Magnetron()
    mag.start()
    println("Game start")
    printState(mag.currentState)

    while(!mag.isFinished) {
        mag.performAction(mag.possibleActions.random())
        println("Round ${mag.gameStates.size}")
        printState(mag.currentState)
        mag.currentStatePlayerViews.forEach { state -> printState(state.state) }
    }

    val winners = mag.winnerAvatarIndices
    println("Winner: $winners")
}
